import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const html = readFileSync(new URL('../server/public/index.html', import.meta.url), 'utf8');
const script = readFileSync(new URL('../server/public/script.js', import.meta.url), 'utf8');
const weatherScript = readFileSync(new URL('../server/public/weather-workspace.js', import.meta.url), 'utf8');
const settingsScript = readFileSync(new URL('../server/public/settings-workspace.js', import.meta.url), 'utf8');
const styles = readFileSync(new URL('../server/public/navigation-weather.css', import.meta.url), 'utf8');

describe('navigation, settings, and weather workspace contract', () => {
  it('keeps Dashboard and Command as separate primary workspaces', () => {
    const nav = html.slice(html.indexOf('<nav class="app-primary-nav"'), html.indexOf('</nav>', html.indexOf('<nav class="app-primary-nav"')));
    expect(nav).toMatch(/data-view="overview" data-nav-key="dashboard"/);
    expect(nav).toMatch(/data-view="incident" data-nav-key="command"/);
    expect(nav).not.toContain('data-nav-key="dashboard" aria-label="Open Command Dashboard"');
    expect(html).toContain('class="module-btn command-brand-home"');
    expect(script).toContain("showView('overview');");
  });

  it('removes Sources and Planning from the primary nav without deleting their workspaces', () => {
    const nav = html.slice(html.indexOf('<nav class="app-primary-nav"'), html.indexOf('</nav>', html.indexOf('<nav class="app-primary-nav"')));
    expect(nav).not.toMatch(/data-view="source"|data-view="planning-tools"/);
    expect(html).toContain('<section id="planning-tools"');
    expect(html).toContain('<section id="source"');
    expect(html).toContain('<button class="module-btn overview-action-btn overview-action-planning"');
  });

  it('provides a real persisted Settings workspace and shared theme state', () => {
    expect(html).toContain('<section id="settings" class="view settings-page"');
    expect(html).toContain('data-theme-choice="dark"');
    expect(html).toContain('data-theme-choice="light"');
    expect(html).toContain('id="settings-sources-toggle"');
    expect(script).toContain("window.localStorage.setItem('hazmatiq-theme', normalized)");
    expect(settingsScript).toContain('initializeSettingsPage');
    expect(styles).toContain('[data-theme="light"]');
  });

  it('provides standalone Weather Intelligence over the shared weather/radar infrastructure', () => {
    expect(html).toContain('<section id="weather" class="view weather-intelligence-page"');
    expect(html).toContain('id="weather-map"');
    expect(html).toContain('id="weather-radar-source"');
    expect(html).toContain('id="weather-location-form"');
    expect(html).toContain('data-weather-layer="radar"');
    expect(html).toContain('data-weather-layer="alerts"');
    expect(html).toContain('id="weather-layer-wind"');
    expect(html).toContain('id="weather-layer-flood"');
    expect(html).toContain('id="weather-layer-fire"');
    expect(html).toContain('data-weather-wind-time="0"');
    expect(html).toContain('data-weather-wind-time="6"');
    expect(html).toContain('weather-flood-service-status');
    expect(html).toContain('Operational Impacts');
    expect(html).toContain('Weather effects relevant to current operations');
    expect(html).toContain('class="weather-forecast-panel" id="weather-forecast-panel"');
    expect(html).toContain('class="weather-conditions-dropdown" id="weather-services-dropdown"');
    expect(html).not.toContain('Field conditions and source availability');
    expect(html).toContain('class="weather-conditions-layout"');
    expect(html).toContain('class="weather-forecast-title-graphic"');
    expect(html).toContain('weather-forecast-panel');
    expect(html).not.toContain('1, 6, 12, and 24 hour outlook');
    expect(html).not.toContain('id="weather-forecast-dropdown"');
    expect(html).not.toContain('class="weather-intelligence-card"><header><div><p class="eyebrow">Forward Look</p>');
    expect(styles).toContain('background: linear-gradient(135deg, #eaf8fc 0%, #d8eef8 100%) !important;');
    expect(styles).toContain('color: #102a43 !important;');
    expect(styles).toContain('grid-template-columns: repeat(3, minmax(0, 1fr));');
    expect(styles).toContain('.weather-forecast-card-graphic');
    expect(styles).toContain('font-size: .68rem;');
    expect(styles).toContain('font-weight: 950;');
    expect(html).toContain('id="weather-impact-more"');
    expect(html).toContain('id="weather-send-to-command"');
    expect(html).not.toContain('weather-alert-groups');
    expect(html).not.toMatch(/id="weather-layer-(alerts|wind|flood|fire)"[^>]*disabled/);
    expect(html).not.toContain('Real-Time Operational Weather.</p>');
    expect(html).not.toContain('weather-incident-context');
    expect(html).not.toContain('Use Incident Location');
    expect(script).toContain('window.HazMatIQ.weatherService = {');
    expect(script).toContain('cacheAgeMs < 5 * 60 * 1000');
    expect(script).toContain("window.dispatchEvent(new CustomEvent('hazmatiq:weather-updated'");
    expect(weatherScript).toContain('hazscope_weather_location');
    expect(weatherScript).toContain('/api/weather/alerts');
    expect(weatherScript).toContain('/api/weather/wind');
    expect(weatherScript).toContain('/api/hydrology/flood');
    expect(weatherScript).toContain('moveend');
    expect(weatherScript).toContain('AbortController');
    expect(weatherScript).toContain('Open-Meteo 10 m forecast grid');
    expect(weatherScript).toContain('incidentCommandLegacy?.getActiveIncident');
    expect(weatherScript).not.toContain('activeIncident()');
    expect(weatherScript).toContain('HazMatWeatherRadar.createController');
    expect(weatherScript).toContain('renderWindOverlay');
    expect(weatherScript).toContain('showWindPopup');
    expect(weatherScript).toContain('closeWeatherPopups');
    expect(weatherScript).toContain('Arrow shows the direction the wind travels.');
    expect(weatherScript).toContain('formatAlertTimeWindow');
    expect(weatherScript).toContain('weather-impact-time');
    expect(weatherScript).toContain('weather-impact-map-target');
    expect(weatherScript).toContain('flashAlertOnMap');
    expect(weatherScript).toContain('weather-alert-highlight');
    expect(weatherScript).toContain('properties.sent || properties.effective || properties.onset');
    expect(weatherScript).toContain("`${impacts.length} IMPACTS`");
    expect(styles).toContain('.weather-impact-time');
    expect(styles).toContain('.weather-impact-map-target');
    expect(styles).toContain('.weather-impact-map-hint');
    expect(styles).toContain('.weather-impact-critical .weather-impact-heading strong');
    expect(styles).toContain('.weather-impact-significant .weather-impact-heading strong');
    expect(styles).toContain('color: #ff4d5a !important;');
    expect(styles).toContain('color: #f6c343 !important;');
    expect(weatherScript).toContain('badge.textContent = impact.severity.toUpperCase()');
    expect(weatherScript).toContain('return [1, 6, 12, 24].map');
    expect(weatherScript).toContain('function createForecastGraphic');
    expect(weatherScript).toContain('forecastWeatherKind');
    expect(weatherScript).toContain("windPart: 'arrowhead'");
    expect(weatherScript).toContain("id: windArrowLayerId");
    expect(weatherScript).not.toContain('line-dasharray');
    expect(weatherScript).not.toContain("'text-field': '➤'");
    expect(weatherScript).toContain('weatherFirePopupFeatureId === featureId');
    expect(weatherScript).toContain('loadFireOverlay');
    expect(weatherScript).toContain('buildOperationalWeatherImpacts');
    expect(weatherScript).toContain('angularDifference');
    expect(weatherScript).toContain('sendWeatherAssessmentToCommand');
    expect(weatherScript).toContain('weatherBriefs: [...briefs, record]');
    expect(weatherScript).toContain('mapInfrastructure');
    expect(script).toContain('WEATHER_BRIEF');
    expect(script).toContain('appendWeatherBriefsToIncidentReport');
    expect(html).toContain('Send Weather Brief to Command');
  });
});
